#! /bin/sh

cd $HOME

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
[ -f "$XDG_CONFIG_HOME/dwm/startup" ] && . $XDG_CONFIG_HOME/dwm/startup

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
mkdir -p "$XDG_CACHE_HOME/dwm"

logfile="$XDG_CACHE_HOME/dwm/log"

[ -f "$logfile" ] && cp "$logfile" "$logfile.old"

command -v slstatus && slstatus 2> /dev/null &
command -v dunst && dunst &
exec dwm 2> "$logfile"
